define unknown = Character("???", color="#A9A9A9")
define mc = Character("[player_name]", color="#228B22")
define ar = Character('Артём', color="#8e6fff")
define il = Character('Илья', color="#81ffff")
define po = Character("Полина", color="#8B4513")
define na = Character("Настя", color="#FF69B4")
define dv = Character("Дмитрий Валерьевич", color="#708090")
define mu = Character("Мурашов", color="#8B0000")
define ka = Character("Катя", color="#9932CC")